# Generated by Django 5.0.7 on 2025-03-14 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontendform", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="djangoplaindata",
            old_name="date_of_birthday",
            new_name="date_of_birth",
        ),
    ]
