# Generated by Django 5.0.7 on 2025-03-14 03:46

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontendform", "0002_rename_date_of_birthday_djangoplaindata_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoEncryptedDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", encrypted_model_fields.fields.EncryptedCharField()),
                ("email", encrypted_model_fields.fields.EncryptedEmailField()),
                ("date_of_birth", encrypted_model_fields.fields.EncryptedDateField()),
            ],
        ),
        migrations.RenameModel(
            old_name="DjangoPlainData",
            new_name="DjangoPlainDataModel",
        ),
    ]
